### PR TITLE
Add battery charge & discharge totals to Sensor.py for use in Home Assistant energy page. 

### PR DESCRIPTION
**Pull request by slackwilson**
Feel free to change the naming if you like, all I did was add in the 2 sensors for charge & discharge in kWh

### CODE REVIEW

**Comment by richo** [comment]
Looks good! I am gunna change the names just to make them consistent with the others but this is great.

**Comment by richo** [comment]
Pulled into main, and I updated the class names and property names to make them consistent with what else is there in cd456161e0ee1c66aa3d8ad4bf59ff31b3644cc8, I hope that's ok. Hopefully that doesn't wreak havoc with your install when you pull this in.

**Comment by slackwilson** [comment]
Yer of course, I was playing around and used some names that I could tell at a glance were the ones I added, as you say better to keep it more consistent :)

**Comment by slackwilson** [comment]
just an update, the name change caused zero issues - I run those through a Helper because they naturally reset daily just after midnight which the HA energy page doesn't like - and the helper picked up the new names automatically so I didn't have to do anything it just worked.

**Pull request closed without merging**
